version: "1.0.0"
services:
  search-pdf:
    image: jankorinek/search_pdf:latest
    environment:
      - TZ=Europe/Prague
    volumes:
      - type: bind
        source: /data
        target: /output
      - type: volume
        source: mydata
        target: /data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build:
      context: .
      dockerfile: Dockerfile
volumes:
  mydata: